<div class="flex flex-col gap-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div class="flex flex-col gap-1">
            <div class="flex items-center gap-2 text-sm font-medium text-brand-500 dark:text-brand-400">
                <svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 21V11M12 14c-4.5 0-7-2.5-7-7 4.5 0 7 2.5 7 7Zm0-3c0-4.5 2.5-7 7-7 0 4.5-2.5 7-7 7Z" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" /></svg>
                Personal
            </div>
            <h1 class="text-2xl font-semibold tracking-tight text-gray-900 dark:text-white">Empleados</h1>
            <p class="max-w-2xl text-sm text-gray-500 dark:text-gray-400">Administra la información personal, laboral y la cuenta opcional de cada trabajador.</p>
        </div>

        @can('create', App\Models\Empleado::class)
            <button type="button" wire:click="openCreateModal" class="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white shadow-theme-xs transition hover:bg-brand-600 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-500">
                <svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 5v14M5 12h14" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" /></svg>
                Nuevo empleado
            </button>
        @endcan
    </div>

    <section aria-labelledby="employees-table-heading" class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]">
        <h2 id="employees-table-heading" class="sr-only">Personal de la empresa</h2>

        <div class="grid grid-cols-1 gap-4 border-b border-gray-200 p-4 dark:border-gray-800 xl:grid-cols-[auto_minmax(18rem,32rem)_auto] xl:items-center xl:justify-between">
            <div class="grid grid-cols-3 rounded-xl bg-gray-100 p-1 dark:bg-gray-900" role="group" aria-label="Filtrar empleados por estado">
                <button type="button" wire:click="$set('status', 'all')" class="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg px-3 text-sm font-semibold transition {{ $status === 'all' ? 'bg-white text-brand-600 shadow-theme-xs dark:bg-gray-800 dark:text-brand-400' : 'text-gray-500 hover:text-gray-800 dark:text-gray-400 dark:hover:text-white' }}">Todos <span class="rounded-full bg-brand-50 px-1.5 py-0.5 text-xs text-brand-600 dark:bg-brand-500/10 dark:text-brand-400">{{ $this->totalEmployees }}</span></button>
                <button type="button" wire:click="$set('status', 'active')" class="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg px-3 text-sm font-semibold transition {{ $status === 'active' ? 'bg-white text-brand-600 shadow-theme-xs dark:bg-gray-800 dark:text-brand-400' : 'text-gray-500 hover:text-gray-800 dark:text-gray-400 dark:hover:text-white' }}">Activos <span class="rounded-full bg-white px-1.5 py-0.5 text-xs text-gray-500 dark:bg-gray-800 dark:text-gray-400">{{ $this->activeEmployees }}</span></button>
                <button type="button" wire:click="$set('status', 'inactive')" class="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg px-3 text-sm font-semibold transition {{ $status === 'inactive' ? 'bg-white text-brand-600 shadow-theme-xs dark:bg-gray-800 dark:text-brand-400' : 'text-gray-500 hover:text-gray-800 dark:text-gray-400 dark:hover:text-white' }}">Retirados <span class="rounded-full bg-white px-1.5 py-0.5 text-xs text-gray-500 dark:bg-gray-800 dark:text-gray-400">{{ $this->totalEmployees - $this->activeEmployees }}</span></button>
            </div>

            <label class="relative block w-full xl:justify-self-center">
                <span class="sr-only">Buscar empleados</span>
                <svg class="pointer-events-none absolute left-3.5 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400" viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="11" cy="11" r="7" stroke="currentColor" stroke-width="1.7" /><path d="m20 20-3.5-3.5" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" /></svg>
                <input type="search" wire:model.live.debounce.350ms="search" placeholder="Buscar por nombre, CI, cargo o correo..." class="h-11 w-full rounded-xl border border-gray-300 bg-transparent py-2.5 pl-11 pr-4 text-sm text-gray-800 outline-none transition placeholder:text-gray-400 focus:border-brand-400 focus:ring-3 focus:ring-brand-500/10 dark:border-gray-700 dark:text-white dark:placeholder:text-gray-500 dark:focus:border-brand-500" />
            </label>

            <div class="hidden items-center justify-end gap-2 text-xs font-medium text-gray-500 xl:flex dark:text-gray-400"><span class="h-2 w-2 rounded-full bg-brand-500"></span>{{ $this->employees->total() }} {{ $this->employees->total() === 1 ? 'resultado' : 'resultados' }}</div>
        </div>

        @if ($this->employees->isEmpty())
            <div class="flex flex-col items-center gap-3 px-6 py-16 text-center">
                <span class="flex h-14 w-14 items-center justify-center rounded-2xl bg-gray-100 text-gray-400 dark:bg-gray-800"><svg class="h-7 w-7" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM3 21v-2a6 6 0 0 1 12 0v2M17 8h4M19 6v4" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" /></svg></span>
                <div><h3 class="font-semibold text-gray-800 dark:text-white/90">No encontramos empleados</h3><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">Prueba con otra búsqueda o registra al primer empleado.</p></div>
                @if ($search !== '' || $status !== 'all')<button type="button" wire:click="$set('search', ''); $set('status', 'all')" class="text-sm font-semibold text-brand-500">Limpiar filtros</button>@endif
            </div>
        @else
            <div class="hidden overflow-x-auto md:block">
                <table class="w-full text-left">
                    <thead class="border-b border-gray-200 bg-gray-50 dark:border-gray-800 dark:bg-gray-900/50">
                        <tr class="text-xs font-semibold uppercase tracking-wide text-gray-500 dark:text-gray-400"><th class="px-5 py-3.5">Empleado</th><th class="px-5 py-3.5">Contacto</th><th class="px-5 py-3.5">Cargo</th><th class="px-5 py-3.5">Cuenta</th><th class="px-5 py-3.5">Estado</th><th class="px-5 py-3.5 text-right">Acciones</th></tr>
                    </thead>
                    <tbody class="divide-y divide-gray-100 dark:divide-gray-800">
                        @foreach ($this->employees as $employee)
                            <tr wire:key="employee-row-{{ $employee->id }}" class="transition hover:bg-gray-50/80 dark:hover:bg-white/[0.02]">
                                <td class="px-5 py-4"><div class="flex items-center gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-sm font-semibold text-brand-600 dark:bg-brand-500/10 dark:text-brand-400">{{ str($employee->nombre_empleado)->substr(0, 1)->upper() }}</span><div><p class="font-semibold text-gray-800 dark:text-white/90">{{ $employee->nombre_completo }}</p><p class="text-sm text-gray-500 dark:text-gray-400">CI {{ $employee->ci_empleado }}</p></div></div></td>
                                <td class="px-5 py-4 text-sm text-gray-600 dark:text-gray-300">{{ $employee->telefono_empleado ?? 'Sin teléfono' }}</td>
                                <td class="px-5 py-4"><p class="text-sm font-medium text-gray-700 dark:text-gray-300">{{ $employee->cargo_empleado }}</p><p class="mt-0.5 text-xs text-gray-400">Ingreso: {{ $employee->fecha_ingreso_empleado?->format('d/m/Y') ?? 'Sin fecha' }}</p></td>
                                <td class="px-5 py-4">@if ($employee->user)<span class="inline-flex flex-col"><span class="text-sm font-medium text-gray-700 dark:text-gray-300">{{ $employee->user->email }}</span><span class="text-xs {{ $employee->user->activo_usuario ? 'text-success-600' : 'text-gray-400' }}">{{ $employee->user->activo_usuario ? 'Acceso habilitado' : 'Acceso bloqueado' }}</span></span>@else<span class="text-sm text-gray-400">Sin cuenta</span>@endif</td>
                                <td class="px-5 py-4"><span class="inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold {{ $employee->activo_empleado ? 'bg-success-50 text-success-700 dark:bg-success-500/10 dark:text-success-400' : 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400' }}"><span class="h-1.5 w-1.5 rounded-full {{ $employee->activo_empleado ? 'bg-success-500' : 'bg-gray-400' }}"></span>{{ $employee->activo_empleado ? 'Activo' : 'Retirado' }}</span></td>
                                <td class="px-5 py-4"><div class="flex justify-end gap-2">@can('update', $employee)<button type="button" wire:click="openEditModal({{ $employee->id }})" class="h-9 rounded-lg border border-gray-300 px-3 text-xs font-semibold text-gray-700 transition hover:bg-gray-50 dark:border-gray-700 dark:text-gray-300 dark:hover:bg-white/[0.05]">Editar</button>@endcan @can('changeStatus', $employee)<button type="button" wire:click="openStatusModal({{ $employee->id }})" class="h-9 rounded-lg px-3 text-xs font-semibold {{ $employee->activo_empleado ? 'bg-error-50 text-error-700 dark:bg-error-500/10 dark:text-error-400' : 'bg-success-50 text-success-700 dark:bg-success-500/10 dark:text-success-400' }}">{{ $employee->activo_empleado ? 'Retirar' : 'Reincorporar' }}</button>@endcan</div></td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

            <div class="divide-y divide-gray-100 md:hidden dark:divide-gray-800">
                @foreach ($this->employees as $employee)
                    <article wire:key="employee-card-{{ $employee->id }}" class="flex flex-col gap-4 p-5">
                        <div class="flex items-start justify-between gap-3"><div><h3 class="font-semibold text-gray-800 dark:text-white/90">{{ $employee->nombre_completo }}</h3><p class="mt-1 text-sm text-gray-500">{{ $employee->cargo_empleado }} · CI {{ $employee->ci_empleado }}</p></div><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $employee->activo_empleado ? 'bg-success-50 text-success-700 dark:bg-success-500/10 dark:text-success-400' : 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400' }}">{{ $employee->activo_empleado ? 'Activo' : 'Retirado' }}</span></div>
                        <dl class="grid grid-cols-2 gap-3 rounded-xl bg-gray-50 p-3 text-xs dark:bg-gray-900/60"><div><dt class="text-gray-500">Teléfono</dt><dd class="mt-1 font-medium text-gray-700 dark:text-gray-300">{{ $employee->telefono_empleado ?? 'Sin registrar' }}</dd></div><div><dt class="text-gray-500">Cuenta</dt><dd class="mt-1 truncate font-medium text-gray-700 dark:text-gray-300">{{ $employee->user?->email ?? 'Sin cuenta' }}</dd></div></dl>
                        <div class="grid grid-cols-2 gap-2">@can('update', $employee)<button type="button" wire:click="openEditModal({{ $employee->id }})" class="h-10 rounded-lg border border-gray-300 text-sm font-semibold text-gray-700 dark:border-gray-700 dark:text-gray-300">Editar</button>@endcan @can('changeStatus', $employee)<button type="button" wire:click="openStatusModal({{ $employee->id }})" class="h-10 rounded-lg text-sm font-semibold {{ $employee->activo_empleado ? 'bg-error-50 text-error-700 dark:bg-error-500/10 dark:text-error-400' : 'bg-success-50 text-success-700 dark:bg-success-500/10 dark:text-success-400' }}">{{ $employee->activo_empleado ? 'Retirar' : 'Reincorporar' }}</button>@endcan</div>
                    </article>
                @endforeach
            </div>

            <div class="border-t border-gray-200 px-5 py-4 dark:border-gray-800">{{ $this->employees->links() }}</div>
        @endif
    </section>

    <div wire:show="showFormModal" x-cloak x-on:employee-form-opened.window="$nextTick(() => $refs.employeeName.focus())" x-on:keydown.escape.window="$wire.closeFormModal()" class="fixed inset-0 z-99999 flex items-end justify-center overflow-y-auto sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-labelledby="employee-form-title">
        <button type="button" wire:click="closeFormModal" class="fixed inset-0 h-full w-full cursor-default bg-gray-950/55 backdrop-blur-sm" aria-label="Cerrar modal"></button>
        <div class="relative max-h-[95vh] w-full overflow-y-auto rounded-t-3xl bg-white shadow-theme-xl sm:max-w-3xl sm:rounded-3xl dark:bg-gray-900">
            <div class="sticky top-0 z-10 flex items-start justify-between gap-4 border-b border-gray-200 bg-white px-5 py-5 sm:px-6 dark:border-gray-800 dark:bg-gray-900"><div><h2 id="employee-form-title" class="text-lg font-semibold text-gray-900 dark:text-white">{{ $editingEmployeeId === null ? 'Registrar empleado' : 'Editar empleado' }}</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">Completa la información personal y laboral. La cuenta de acceso es opcional.</p></div><button type="button" wire:click="closeFormModal" class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-gray-100 text-gray-500 dark:bg-gray-800" aria-label="Cerrar">×</button></div>

            <form wire:submit="save" class="flex flex-col gap-6 p-5 sm:p-6">
                <div class="grid grid-cols-1 gap-5 sm:grid-cols-2">
                    <label class="flex flex-col gap-1.5"><span class="text-sm font-medium text-gray-700 dark:text-gray-300">Nombre <span class="text-error-500">*</span></span><input x-ref="employeeName" type="text" wire:model.blur="form.nombre_empleado" autocomplete="given-name" placeholder="Ej. Pedro" class="h-11 rounded-xl border bg-transparent px-4 text-sm text-gray-800 outline-none focus:ring-3 dark:text-white {{ $errors->has('form.nombre_empleado') ? 'border-error-400 focus:ring-error-500/10' : 'border-gray-300 focus:border-brand-400 focus:ring-brand-500/10 dark:border-gray-700' }}" />@error('form.nombre_empleado')<span class="text-xs text-error-600">{{ $message }}</span>@enderror</label>
                    <label class="flex flex-col gap-1.5"><span class="text-sm font-medium text-gray-700 dark:text-gray-300">Apellido <span class="text-error-500">*</span></span><input type="text" wire:model.blur="form.apellido_empleado" autocomplete="family-name" placeholder="Ej. Quispe" class="h-11 rounded-xl border bg-transparent px-4 text-sm text-gray-800 outline-none focus:ring-3 dark:text-white {{ $errors->has('form.apellido_empleado') ? 'border-error-400 focus:ring-error-500/10' : 'border-gray-300 focus:border-brand-400 focus:ring-brand-500/10 dark:border-gray-700' }}" />@error('form.apellido_empleado')<span class="text-xs text-error-600">{{ $message }}</span>@enderror</label>
                    <label class="flex flex-col gap-1.5"><span class="text-sm font-medium text-gray-700 dark:text-gray-300">Carnet de identidad <span class="text-error-500">*</span></span><input type="text" wire:model.blur="form.ci_empleado" placeholder="Ej. 8456321" class="h-11 rounded-xl border bg-transparent px-4 text-sm text-gray-800 outline-none focus:ring-3 dark:text-white {{ $errors->has('form.ci_empleado') ? 'border-error-400 focus:ring-error-500/10' : 'border-gray-300 focus:border-brand-400 focus:ring-brand-500/10 dark:border-gray-700' }}" />@error('form.ci_empleado')<span class="text-xs text-error-600">{{ $message }}</span>@enderror</label>
                    <label class="flex flex-col gap-1.5"><span class="text-sm font-medium text-gray-700 dark:text-gray-300">Teléfono <span class="font-normal text-gray-400">(opcional)</span></span><input type="tel" wire:model.blur="form.telefono_empleado" autocomplete="tel" placeholder="Ej. 71234567" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4 text-sm text-gray-800 outline-none focus:border-brand-400 focus:ring-3 focus:ring-brand-500/10 dark:border-gray-700 dark:text-white" />@error('form.telefono_empleado')<span class="text-xs text-error-600">{{ $message }}</span>@enderror</label>
                    <label class="flex flex-col gap-1.5 sm:col-span-2"><span class="text-sm font-medium text-gray-700 dark:text-gray-300">Dirección <span class="font-normal text-gray-400">(opcional)</span></span><input type="text" wire:model.blur="form.direccion_empleado" autocomplete="street-address" placeholder="Zona, avenida o calle y número" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4 text-sm text-gray-800 outline-none focus:border-brand-400 focus:ring-3 focus:ring-brand-500/10 dark:border-gray-700 dark:text-white" />@error('form.direccion_empleado')<span class="text-xs text-error-600">{{ $message }}</span>@enderror</label>
                    <label class="flex flex-col gap-1.5"><span class="text-sm font-medium text-gray-700 dark:text-gray-300">Cargo <span class="text-error-500">*</span></span><input type="text" wire:model.blur="form.cargo_empleado" placeholder="Ej. Encargado de almacén" class="h-11 rounded-xl border bg-transparent px-4 text-sm text-gray-800 outline-none focus:ring-3 dark:text-white {{ $errors->has('form.cargo_empleado') ? 'border-error-400 focus:ring-error-500/10' : 'border-gray-300 focus:border-brand-400 focus:ring-brand-500/10 dark:border-gray-700' }}" />@error('form.cargo_empleado')<span class="text-xs text-error-600">{{ $message }}</span>@enderror</label>
                    <label class="flex flex-col gap-1.5"><span class="text-sm font-medium text-gray-700 dark:text-gray-300">Fecha de ingreso <span class="font-normal text-gray-400">(opcional)</span></span><input type="date" wire:model="form.fecha_ingreso_empleado" max="{{ now()->toDateString() }}" class="h-11 rounded-xl border border-gray-300 bg-transparent px-4 text-sm text-gray-800 outline-none focus:border-brand-400 focus:ring-3 focus:ring-brand-500/10 dark:border-gray-700 dark:text-white" />@error('form.fecha_ingreso_empleado')<span class="text-xs text-error-600">{{ $message }}</span>@enderror</label>
                </div>

                @can(App\Enums\PermissionName::EmployeesAssignUser->value)
                    <label class="flex flex-col gap-1.5"><span class="text-sm font-medium text-gray-700 dark:text-gray-300">Cuenta de acceso <span class="font-normal text-gray-400">(opcional)</span></span><select wire:model="form.user_id" @disabled($editingEmployeeId !== null && (int) $form->user_id === (int) auth()->id()) class="h-11 rounded-xl border border-gray-300 bg-transparent px-4 text-sm text-gray-800 outline-none focus:border-brand-400 focus:ring-3 focus:ring-brand-500/10 disabled:cursor-not-allowed disabled:bg-gray-100 dark:border-gray-700 dark:text-white dark:disabled:bg-gray-800"><option value="">Sin cuenta asociada</option>@foreach ($this->availableUsers as $availableUser)<option value="{{ $availableUser->id }}">{{ $availableUser->display_name }} · {{ $availableUser->email }}</option>@endforeach</select>@error('form.user_id')<span class="text-xs text-error-600">{{ $message }}</span>@enderror<span class="text-xs text-gray-500 dark:text-gray-400">Solo aparecen cuentas que todavía no pertenecen a otro empleado.</span></label>
                @endcan

                @if ($editingEmployeeId === null || (int) $form->user_id !== (int) auth()->id())
                    <label class="flex cursor-pointer items-start justify-between gap-4 rounded-xl border border-gray-200 p-4 transition hover:bg-gray-50 dark:border-gray-800 dark:hover:bg-white/[0.02]"><span><span class="block text-sm font-semibold text-gray-800 dark:text-white/90">Empleado activo</span><span class="mt-1 block text-xs leading-5 text-gray-500 dark:text-gray-400">Al retirarlo, su cuenta de acceso también será bloqueada automáticamente.</span></span><input type="checkbox" wire:model="form.activo_empleado" class="peer sr-only" /><span class="relative mt-0.5 h-6 w-11 shrink-0 rounded-full bg-gray-300 transition after:absolute after:left-0.5 after:top-0.5 after:h-5 after:w-5 after:rounded-full after:bg-white after:shadow-sm after:transition peer-checked:bg-brand-500 peer-checked:after:translate-x-5 dark:bg-gray-700"></span></label>
                @endif

                <div class="flex flex-col-reverse gap-3 border-t border-gray-200 pt-5 sm:flex-row sm:justify-end dark:border-gray-800"><button type="button" wire:click="closeFormModal" class="h-11 rounded-xl border border-gray-300 px-5 text-sm font-semibold text-gray-700 dark:border-gray-700 dark:text-gray-300">Cancelar</button><button type="submit" wire:loading.attr="disabled" wire:target="save" class="h-11 rounded-xl bg-brand-500 px-5 text-sm font-semibold text-white hover:bg-brand-600 disabled:opacity-70"><span wire:loading.remove wire:target="save">{{ $editingEmployeeId === null ? 'Registrar empleado' : 'Guardar cambios' }}</span><span wire:loading wire:target="save">Guardando...</span></button></div>
            </form>
        </div>
    </div>

    <div wire:show="showStatusModal" x-cloak x-on:keydown.escape.window="$wire.closeStatusModal()" class="fixed inset-0 z-99999 flex items-center justify-center p-5" role="alertdialog" aria-modal="true" aria-labelledby="employee-status-title">
        <button type="button" wire:click="closeStatusModal" class="fixed inset-0 h-full w-full cursor-default bg-gray-950/55 backdrop-blur-sm" aria-label="Cerrar confirmación"></button>
        <div class="relative w-full max-w-md rounded-3xl bg-white p-6 text-center shadow-theme-xl dark:bg-gray-900"><span class="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl {{ $statusEmployeeIsActive ? 'bg-error-50 text-error-600 dark:bg-error-500/10 dark:text-error-400' : 'bg-success-50 text-success-600 dark:bg-success-500/10 dark:text-success-400' }}"><svg class="h-7 w-7" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 9v4M12 17h.01M10.3 4.4 2.7 18a2 2 0 0 0 1.75 3h15.1a2 2 0 0 0 1.75-3L13.7 4.4a2 2 0 0 0-3.4 0Z" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" /></svg></span><h2 id="employee-status-title" class="mt-5 text-lg font-semibold text-gray-900 dark:text-white">{{ $statusEmployeeIsActive ? '¿Retirar este empleado?' : '¿Reincorporar este empleado?' }}</h2><p class="mt-2 text-sm leading-6 text-gray-500 dark:text-gray-400">@if ($statusEmployeeIsActive)<strong class="font-semibold text-gray-700 dark:text-gray-300">{{ $statusEmployeeName }}</strong> quedará como retirado y su cuenta será bloqueada si tiene una.@else<strong class="font-semibold text-gray-700 dark:text-gray-300">{{ $statusEmployeeName }}</strong> volverá a figurar como activo. Su cuenta deberá habilitarse por separado.@endif</p><div class="mt-6 grid grid-cols-2 gap-3"><button type="button" wire:click="closeStatusModal" class="h-11 rounded-xl border border-gray-300 text-sm font-semibold text-gray-700 dark:border-gray-700 dark:text-gray-300">Cancelar</button><button type="button" wire:click="changeStatus" wire:loading.attr="disabled" wire:target="changeStatus" class="h-11 rounded-xl text-sm font-semibold text-white disabled:opacity-70 {{ $statusEmployeeIsActive ? 'bg-error-500 hover:bg-error-600' : 'bg-success-500 hover:bg-success-600' }}"><span wire:loading.remove wire:target="changeStatus">{{ $statusEmployeeIsActive ? 'Sí, retirar' : 'Sí, reincorporar' }}</span><span wire:loading wire:target="changeStatus">Procesando...</span></button></div></div>
    </div>
</div>
