<div class="flex flex-col gap-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div class="flex flex-col gap-1">
            <div class="flex items-center gap-2 text-sm font-medium text-brand-500 dark:text-brand-400">
                <svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 7h16v10H4zM7 4h10v3M8 11h8M8 14h5" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" /></svg>
                Inventario
            </div>
            <h1 class="text-2xl font-semibold tracking-tight text-gray-900 dark:text-white">Presentaciones de artículos</h1>
            <p class="max-w-2xl text-sm text-gray-500 dark:text-gray-400">Define cómo se solicita o compra cada artículo y su equivalencia con la unidad base de inventario.</p>
        </div>

        @can('create', App\Models\PresentacionArticulo::class)
            <button type="button" wire:click="openCreateModal" class="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white shadow-theme-xs transition hover:bg-brand-600 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-500">
                <svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 5v14M5 12h14" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" /></svg>
                Nueva presentación
            </button>
        @endcan
    </div>

    <section aria-labelledby="article-presentations-table-heading" class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]">
        <h2 id="article-presentations-table-heading" class="sr-only">Listado de presentaciones de artículos</h2>

        <div class="grid grid-cols-1 gap-4 border-b border-gray-200 p-4 dark:border-gray-800 xl:grid-cols-[auto_minmax(18rem,32rem)_auto] xl:items-center xl:justify-between">
            <div class="grid grid-cols-3 rounded-xl bg-gray-100 p-1 dark:bg-gray-900" role="group" aria-label="Filtrar presentaciones por estado">
                <button type="button" wire:click="$set('status', 'all')" class="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg px-3 text-sm font-semibold transition {{ $status === 'all' ? 'bg-white text-brand-600 shadow-theme-xs dark:bg-gray-800 dark:text-brand-400' : 'text-gray-500 hover:text-gray-800 dark:text-gray-400 dark:hover:text-white' }}">Todas <span class="rounded-full bg-brand-50 px-1.5 py-0.5 text-xs text-brand-600 dark:bg-brand-500/10 dark:text-brand-400">{{ $this->totalPresentations }}</span></button>
                <button type="button" wire:click="$set('status', 'active')" class="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg px-3 text-sm font-semibold transition {{ $status === 'active' ? 'bg-white text-brand-600 shadow-theme-xs dark:bg-gray-800 dark:text-brand-400' : 'text-gray-500 hover:text-gray-800 dark:text-gray-400 dark:hover:text-white' }}">Activas <span class="rounded-full bg-white px-1.5 py-0.5 text-xs text-gray-500 dark:bg-gray-800 dark:text-gray-400">{{ $this->activePresentations }}</span></button>
                <button type="button" wire:click="$set('status', 'inactive')" class="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg px-3 text-sm font-semibold transition {{ $status === 'inactive' ? 'bg-white text-brand-600 shadow-theme-xs dark:bg-gray-800 dark:text-brand-400' : 'text-gray-500 hover:text-gray-800 dark:text-gray-400 dark:hover:text-white' }}">Inactivas <span class="rounded-full bg-white px-1.5 py-0.5 text-xs text-gray-500 dark:bg-gray-800 dark:text-gray-400">{{ $this->totalPresentations - $this->activePresentations }}</span></button>
            </div>

            <label class="relative block w-full xl:justify-self-center">
                <span class="sr-only">Buscar presentaciones</span>
                <svg class="pointer-events-none absolute left-3.5 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400" viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="11" cy="11" r="7" stroke="currentColor" stroke-width="1.7" /><path d="m20 20-3.5-3.5" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" /></svg>
                <input type="search" wire:model.live.debounce.350ms="search" placeholder="Buscar presentación, artículo o unidad..." class="h-11 w-full rounded-xl border border-gray-300 bg-transparent py-2.5 pl-11 pr-4 text-sm text-gray-800 outline-none transition placeholder:text-gray-400 focus:border-brand-400 focus:ring-3 focus:ring-brand-500/10 dark:border-gray-700 dark:text-white dark:placeholder:text-gray-500 dark:focus:border-brand-500" />
            </label>

            <div class="hidden items-center justify-end gap-2 text-xs font-medium text-gray-500 xl:flex dark:text-gray-400"><span class="h-2 w-2 rounded-full bg-brand-500"></span>{{ $this->presentations->total() }} {{ $this->presentations->total() === 1 ? 'resultado' : 'resultados' }}</div>
        </div>

        @if ($this->presentations->isEmpty())
            <div class="flex flex-col items-center gap-4 px-6 py-16 text-center">
                <span class="flex h-16 w-16 items-center justify-center rounded-2xl bg-brand-50 text-brand-500 dark:bg-brand-500/10 dark:text-brand-400"><svg class="h-8 w-8" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 7h16v10H4zM7 4h10v3M8 11h8M8 14h5" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" /></svg></span>
                <div><h3 class="font-semibold text-gray-800 dark:text-white/90">No se encontraron presentaciones</h3><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">{{ $search !== '' || $status !== 'all' ? 'Prueba con otros criterios de búsqueda.' : 'Registra la primera presentación para comenzar.' }}</p></div>
                @if ($search !== '' || $status !== 'all')<button type="button" wire:click="clearFilters" class="text-sm font-semibold text-brand-500 hover:text-brand-600">Limpiar filtros</button>@endif
            </div>
        @else
            <div class="hidden overflow-x-auto md:block">
                <table class="w-full min-w-[1280px] text-left">
                    <thead class="border-b border-gray-200 bg-gray-50/80 text-xs font-semibold uppercase tracking-wide text-gray-500 dark:border-gray-800 dark:bg-white/[0.02] dark:text-gray-400"><tr><th class="px-5 py-3.5">Presentación</th><th class="px-5 py-3.5">Artículo</th><th class="px-5 py-3.5">Uso</th><th class="px-5 py-3.5">Equivalencia</th><th class="px-5 py-3.5">Predeterminada</th><th class="px-5 py-3.5">Estado</th><th class="px-5 py-3.5 text-right">Acciones</th></tr></thead>
                    <tbody class="divide-y divide-gray-100 dark:divide-gray-800">
                        @foreach ($this->presentations as $presentacionArticulo)
                            <tr wire:key="article-presentation-row-{{ $presentacionArticulo->id }}" class="transition hover:bg-gray-50/80 dark:hover:bg-white/[0.02]">
                                <td class="px-5 py-4"><span class="font-semibold text-gray-800 dark:text-white/90">{{ $presentacionArticulo->nombre_presentacion_articulo }}</span></td>
                                <td class="px-5 py-4"><div class="flex items-center gap-3">@if ($presentacionArticulo->articulo->imagen_articulo)<img src="{{ $presentacionArticulo->articulo->imagen_url }}" alt="{{ $presentacionArticulo->articulo->nombre_articulo }}" loading="lazy" class="h-10 w-10 shrink-0 rounded-xl border border-gray-200 object-cover dark:border-gray-700" />@else<span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-500/10 dark:text-brand-400"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 4h14v16H5zM8 8h8M8 12h8" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" /></svg></span>@endif<div><p class="font-medium text-gray-700 dark:text-gray-300">{{ $presentacionArticulo->articulo->nombre_articulo }}</p><p class="mt-0.5 text-xs text-gray-400">Unidad base: {{ $presentacionArticulo->articulo->unidadMedida->abreviatura_unidad_medida }}</p></div></div></td>
                                <td class="px-5 py-4"><span class="inline-flex rounded-full bg-brand-50 px-2.5 py-1 text-xs font-semibold text-brand-700 dark:bg-brand-500/10 dark:text-brand-400">{{ $presentacionArticulo->uso_presentacion_articulo->label() }}</span></td>
                                <td class="px-5 py-4"><div class="flex flex-col gap-1">@if ($presentacionArticulo->equivalencia_base_presentacion_articulo !== null)<span class="font-mono text-sm font-semibold text-gray-700 dark:text-gray-300">{{ number_format((float) $presentacionArticulo->equivalencia_base_presentacion_articulo, 3, ',', '.') }} {{ $presentacionArticulo->articulo->unidadMedida->abreviatura_unidad_medida }}</span>@else<span class="text-sm text-gray-400">Sin valor fijo</span>@endif<span class="text-xs text-gray-400">{{ $presentacionArticulo->tipo_equivalencia_presentacion_articulo->label() }} · {{ $presentacionArticulo->permite_fraccion_presentacion_articulo ? 'Admite fracción' : 'Solo cantidades enteras' }}</span></div></td>
                                <td class="px-5 py-4"><div class="flex flex-wrap gap-1.5">@if ($presentacionArticulo->predeterminada_pedido_presentacion_articulo)<span class="rounded-full bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-700 dark:bg-blue-500/10 dark:text-blue-400">Pedido</span>@endif @if ($presentacionArticulo->predeterminada_compra_presentacion_articulo)<span class="rounded-full bg-amber-50 px-2 py-1 text-xs font-semibold text-amber-700 dark:bg-amber-500/10 dark:text-amber-400">Compra</span>@endif @if (! $presentacionArticulo->predeterminada_pedido_presentacion_articulo && ! $presentacionArticulo->predeterminada_compra_presentacion_articulo)<span class="text-sm text-gray-400">No</span>@endif</div></td>
                                <td class="px-5 py-4"><span class="inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold {{ $presentacionArticulo->estado_presentacion_articulo ? 'bg-success-50 text-success-700 dark:bg-success-500/10 dark:text-success-400' : 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400' }}"><span class="h-1.5 w-1.5 rounded-full {{ $presentacionArticulo->estado_presentacion_articulo ? 'bg-success-500' : 'bg-gray-400' }}"></span>{{ $presentacionArticulo->estado_presentacion_articulo ? 'Activa' : 'Inactiva' }}</span></td>
                                <td class="px-5 py-4"><div class="flex justify-end gap-2">@can('update', $presentacionArticulo)<button type="button" wire:click="openEditModal({{ $presentacionArticulo->id }})" class="h-9 rounded-lg border border-gray-300 px-3 text-xs font-semibold text-gray-700 transition hover:bg-gray-50 dark:border-gray-700 dark:text-gray-300 dark:hover:bg-white/[0.05]">Editar</button>@endcan @can('changeStatus', $presentacionArticulo)<button type="button" wire:click="openStatusModal({{ $presentacionArticulo->id }})" class="h-9 rounded-lg px-3 text-xs font-semibold {{ $presentacionArticulo->estado_presentacion_articulo ? 'bg-error-50 text-error-700 dark:bg-error-500/10 dark:text-error-400' : 'bg-success-50 text-success-700 dark:bg-success-500/10 dark:text-success-400' }}">{{ $presentacionArticulo->estado_presentacion_articulo ? 'Desactivar' : 'Activar' }}</button>@endcan</div></td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

            <div class="divide-y divide-gray-100 md:hidden dark:divide-gray-800">
                @foreach ($this->presentations as $presentacionArticulo)
                    <article wire:key="article-presentation-card-{{ $presentacionArticulo->id }}" class="flex flex-col gap-4 p-5">
                        <div class="flex items-start gap-3">@if ($presentacionArticulo->articulo->imagen_articulo)<img src="{{ $presentacionArticulo->articulo->imagen_url }}" alt="{{ $presentacionArticulo->articulo->nombre_articulo }}" loading="lazy" class="h-14 w-14 shrink-0 rounded-xl border border-gray-200 object-cover dark:border-gray-700" />@else<span class="flex h-14 w-14 shrink-0 items-center justify-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-500/10 dark:text-brand-400"><svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 4h14v16H5zM8 8h8M8 12h8" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" /></svg></span>@endif<div class="min-w-0 grow"><h3 class="truncate font-semibold text-gray-800 dark:text-white/90">{{ $presentacionArticulo->nombre_presentacion_articulo }}</h3><p class="mt-1 truncate text-sm text-gray-500">{{ $presentacionArticulo->articulo->nombre_articulo }}</p></div><span class="shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold {{ $presentacionArticulo->estado_presentacion_articulo ? 'bg-success-50 text-success-700 dark:bg-success-500/10 dark:text-success-400' : 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400' }}">{{ $presentacionArticulo->estado_presentacion_articulo ? 'Activa' : 'Inactiva' }}</span></div>
                        <div class="grid grid-cols-2 gap-2 rounded-xl bg-gray-50 px-3 py-2.5 text-sm dark:bg-gray-900/60"><div><span class="block text-xs text-gray-500">Uso</span><span class="font-semibold text-gray-700 dark:text-gray-300">{{ $presentacionArticulo->uso_presentacion_articulo->label() }}</span></div><div><span class="block text-xs text-gray-500">Equivalencia</span><span class="font-semibold text-gray-700 dark:text-gray-300">{{ $presentacionArticulo->equivalencia_base_presentacion_articulo !== null ? number_format((float) $presentacionArticulo->equivalencia_base_presentacion_articulo, 3, ',', '.').' '.$presentacionArticulo->articulo->unidadMedida->abreviatura_unidad_medida : 'Variable' }}</span></div><div><span class="block text-xs text-gray-500">Tipo</span><span class="font-semibold text-gray-700 dark:text-gray-300">{{ $presentacionArticulo->tipo_equivalencia_presentacion_articulo->label() }}</span></div><div><span class="block text-xs text-gray-500">Cantidad</span><span class="font-semibold text-gray-700 dark:text-gray-300">{{ $presentacionArticulo->permite_fraccion_presentacion_articulo ? 'Admite fracción' : 'Entera' }}</span></div></div>
                        <div class="grid grid-cols-2 gap-2">@can('update', $presentacionArticulo)<button type="button" wire:click="openEditModal({{ $presentacionArticulo->id }})" class="h-10 rounded-lg border border-gray-300 text-sm font-semibold text-gray-700 dark:border-gray-700 dark:text-gray-300">Editar</button>@endcan @can('changeStatus', $presentacionArticulo)<button type="button" wire:click="openStatusModal({{ $presentacionArticulo->id }})" class="h-10 rounded-lg text-sm font-semibold {{ $presentacionArticulo->estado_presentacion_articulo ? 'bg-error-50 text-error-700 dark:bg-error-500/10 dark:text-error-400' : 'bg-success-50 text-success-700 dark:bg-success-500/10 dark:text-success-400' }}">{{ $presentacionArticulo->estado_presentacion_articulo ? 'Desactivar' : 'Activar' }}</button>@endcan</div>
                    </article>
                @endforeach
            </div>

            <div class="border-t border-gray-200 px-5 py-4 dark:border-gray-800">{{ $this->presentations->links() }}</div>
        @endif
    </section>

    <div wire:show="showFormModal" x-cloak x-on:article-presentation-form-opened.window="$nextTick(() => $refs.presentationArticle.focus())" x-on:keydown.escape.window="$wire.closeFormModal()" class="fixed inset-0 z-99999 flex items-end justify-center overflow-y-auto sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-labelledby="article-presentation-form-title">
        <button type="button" wire:click="closeFormModal" class="fixed inset-0 h-full w-full cursor-default bg-gray-950/55 backdrop-blur-sm" aria-label="Cerrar modal"></button>
        <div class="relative max-h-[95vh] w-full overflow-y-auto rounded-t-3xl bg-white shadow-theme-xl sm:max-w-2xl sm:rounded-3xl dark:bg-gray-900">
            <div class="sticky top-0 z-10 flex items-start justify-between gap-4 border-b border-gray-200 bg-white px-5 py-5 sm:px-6 dark:border-gray-800 dark:bg-gray-900"><div><h2 id="article-presentation-form-title" class="text-lg font-semibold text-gray-900 dark:text-white">{{ $editingPresentationId === null ? 'Registrar presentación' : 'Editar presentación' }}</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">Relaciona la presentación con un artículo y su cantidad equivalente.</p></div><button type="button" wire:click="closeFormModal" class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-gray-100 text-gray-500 transition hover:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700" aria-label="Cerrar">×</button></div>

            <form wire:submit="save" class="flex flex-col gap-5 p-5 sm:p-6">
                <label class="flex flex-col gap-1.5"><span class="text-sm font-medium text-gray-700 dark:text-gray-300">Artículo <span class="text-error-500">*</span></span><select x-ref="presentationArticle" wire:model="form.articulo_id" class="h-11 rounded-xl border bg-transparent px-4 text-sm text-gray-800 outline-none focus:ring-3 dark:bg-gray-900 dark:text-white {{ $errors->has('form.articulo_id') ? 'border-error-400 focus:ring-error-500/10' : 'border-gray-300 focus:border-brand-400 focus:ring-brand-500/10 dark:border-gray-700' }}"><option value="">Selecciona un artículo</option>@foreach ($this->articleOptions as $articulo)<option value="{{ $articulo->id }}">{{ $articulo->nombre_articulo }} · {{ $articulo->unidadMedida->abreviatura_unidad_medida }}</option>@endforeach</select>@error('form.articulo_id')<span class="text-xs text-error-600">{{ $message }}</span>@enderror</label>

                <label class="flex flex-col gap-1.5"><span class="text-sm font-medium text-gray-700 dark:text-gray-300">Nombre de la presentación <span class="text-error-500">*</span></span><input type="text" wire:model.blur="form.nombre_presentacion_articulo" autocomplete="off" placeholder="Ej. Caja completa" class="h-11 rounded-xl border bg-transparent px-4 text-sm text-gray-800 outline-none focus:ring-3 dark:text-white {{ $errors->has('form.nombre_presentacion_articulo') ? 'border-error-400 focus:ring-error-500/10' : 'border-gray-300 focus:border-brand-400 focus:ring-brand-500/10 dark:border-gray-700' }}" />@error('form.nombre_presentacion_articulo')<span class="text-xs text-error-600">{{ $message }}</span>@enderror</label>

                <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
                    <label class="flex flex-col gap-1.5"><span class="text-sm font-medium text-gray-700 dark:text-gray-300">Uso <span class="text-error-500">*</span></span><select wire:model.live="form.uso_presentacion_articulo" class="h-11 rounded-xl border bg-transparent px-4 text-sm text-gray-800 outline-none focus:ring-3 dark:bg-gray-900 dark:text-white {{ $errors->has('form.uso_presentacion_articulo') ? 'border-error-400 focus:ring-error-500/10' : 'border-gray-300 focus:border-brand-400 focus:ring-brand-500/10 dark:border-gray-700' }}">@foreach (App\Enums\UsoPresentacionArticulo::cases() as $uso)<option value="{{ $uso->value }}">{{ $uso->label() }}</option>@endforeach</select>@error('form.uso_presentacion_articulo')<span class="text-xs text-error-600">{{ $message }}</span>@enderror</label>

                    <label class="flex flex-col gap-1.5"><span class="text-sm font-medium text-gray-700 dark:text-gray-300">Tipo de equivalencia <span class="text-error-500">*</span></span><select wire:model.live="form.tipo_equivalencia_presentacion_articulo" class="h-11 rounded-xl border bg-transparent px-4 text-sm text-gray-800 outline-none focus:ring-3 dark:bg-gray-900 dark:text-white {{ $errors->has('form.tipo_equivalencia_presentacion_articulo') ? 'border-error-400 focus:ring-error-500/10' : 'border-gray-300 focus:border-brand-400 focus:ring-brand-500/10 dark:border-gray-700' }}">@foreach (App\Enums\TipoEquivalenciaPresentacionArticulo::cases() as $tipoEquivalencia)<option value="{{ $tipoEquivalencia->value }}">{{ $tipoEquivalencia->label() }}</option>@endforeach</select>@error('form.tipo_equivalencia_presentacion_articulo')<span class="text-xs text-error-600">{{ $message }}</span>@enderror</label>
                </div>

                @if ($form->tipo_equivalencia_presentacion_articulo !== App\Enums\TipoEquivalenciaPresentacionArticulo::Variable->value)
                    <label class="flex flex-col gap-1.5"><span class="text-sm font-medium text-gray-700 dark:text-gray-300">Equivalencia con la unidad base <span class="text-error-500">*</span></span><input type="number" wire:model.blur="form.equivalencia_base_presentacion_articulo" min="0.001" max="9999999.999" step="0.001" inputmode="decimal" placeholder="Ej. 20.000" class="h-11 rounded-xl border bg-transparent px-4 text-sm text-gray-800 outline-none focus:ring-3 dark:text-white {{ $errors->has('form.equivalencia_base_presentacion_articulo') ? 'border-error-400 focus:ring-error-500/10' : 'border-gray-300 focus:border-brand-400 focus:ring-brand-500/10 dark:border-gray-700' }}" /><span class="text-xs leading-5 text-gray-500 dark:text-gray-400">Cantidad que representa una presentación en la unidad base del artículo. Puede tener hasta 3 decimales.</span>@error('form.equivalencia_base_presentacion_articulo')<span class="text-xs text-error-600">{{ $message }}</span>@enderror</label>
                @else
                    <div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-800 dark:border-amber-500/20 dark:bg-amber-500/10 dark:text-amber-300">La equivalencia se registrará cuando se conozca la cantidad base real de cada operación.</div>
                @endif

                <label class="flex cursor-pointer items-start justify-between gap-4 rounded-xl border border-gray-200 p-4 transition hover:bg-gray-50 dark:border-gray-800 dark:hover:bg-white/[0.02]"><span><span class="block text-sm font-semibold text-gray-800 dark:text-white/90">Permite cantidades fraccionadas</span><span class="mt-1 block text-xs leading-5 text-gray-500 dark:text-gray-400">Actívalo si se puede registrar, por ejemplo, 0.5 o 1.5 presentaciones.</span></span><input type="checkbox" wire:model="form.permite_fraccion_presentacion_articulo" class="peer sr-only" /><span class="relative mt-0.5 h-6 w-11 shrink-0 rounded-full bg-gray-300 transition after:absolute after:left-0.5 after:top-0.5 after:h-5 after:w-5 after:rounded-full after:bg-white after:shadow-sm after:transition peer-checked:bg-brand-500 peer-checked:after:translate-x-5 dark:bg-gray-700"></span></label>

                @if ($form->estado_presentacion_articulo)
                    <div class="grid grid-cols-1 gap-3 sm:grid-cols-2">
                        @if ($form->uso_presentacion_articulo !== App\Enums\UsoPresentacionArticulo::Compra->value)
                            <label class="flex cursor-pointer items-start justify-between gap-3 rounded-xl border border-gray-200 p-4 dark:border-gray-800"><span><span class="block text-sm font-semibold text-gray-800 dark:text-white/90">Predeterminada para pedido</span><span class="mt-1 block text-xs leading-5 text-gray-500 dark:text-gray-400">Reemplazará la predeterminada anterior.</span></span><input type="checkbox" wire:model="form.predeterminada_pedido_presentacion_articulo" class="peer sr-only" /><span class="relative mt-0.5 h-6 w-11 shrink-0 rounded-full bg-gray-300 transition after:absolute after:left-0.5 after:top-0.5 after:h-5 after:w-5 after:rounded-full after:bg-white after:shadow-sm after:transition peer-checked:bg-brand-500 peer-checked:after:translate-x-5 dark:bg-gray-700"></span></label>
                        @endif

                        @if ($form->uso_presentacion_articulo !== App\Enums\UsoPresentacionArticulo::Pedido->value)
                            <label class="flex cursor-pointer items-start justify-between gap-3 rounded-xl border border-gray-200 p-4 dark:border-gray-800"><span><span class="block text-sm font-semibold text-gray-800 dark:text-white/90">Predeterminada para compra</span><span class="mt-1 block text-xs leading-5 text-gray-500 dark:text-gray-400">Reemplazará la predeterminada anterior.</span></span><input type="checkbox" wire:model="form.predeterminada_compra_presentacion_articulo" class="peer sr-only" /><span class="relative mt-0.5 h-6 w-11 shrink-0 rounded-full bg-gray-300 transition after:absolute after:left-0.5 after:top-0.5 after:h-5 after:w-5 after:rounded-full after:bg-white after:shadow-sm after:transition peer-checked:bg-brand-500 peer-checked:after:translate-x-5 dark:bg-gray-700"></span></label>
                        @endif
                    </div>
                @endif

                @if ($editingPresentationId === null || auth()->user()->can(App\Enums\PermissionName::ArticlePresentationsChangeStatus->value))
                    <label class="flex cursor-pointer items-start justify-between gap-4 rounded-xl border border-gray-200 p-4 transition hover:bg-gray-50 dark:border-gray-800 dark:hover:bg-white/[0.02]"><span><span class="block text-sm font-semibold text-gray-800 dark:text-white/90">Presentación activa</span><span class="mt-1 block text-xs leading-5 text-gray-500 dark:text-gray-400">Las presentaciones inactivas conservan su historial, pero no estarán disponibles para nuevas operaciones.</span></span><input type="checkbox" wire:model.live="form.estado_presentacion_articulo" class="peer sr-only" /><span class="relative mt-0.5 h-6 w-11 shrink-0 rounded-full bg-gray-300 transition after:absolute after:left-0.5 after:top-0.5 after:h-5 after:w-5 after:rounded-full after:bg-white after:shadow-sm after:transition peer-checked:bg-brand-500 peer-checked:after:translate-x-5 dark:bg-gray-700"></span></label>
                @endif

                <div class="flex flex-col-reverse gap-3 border-t border-gray-200 pt-5 sm:flex-row sm:justify-end dark:border-gray-800"><button type="button" wire:click="closeFormModal" class="h-11 rounded-xl border border-gray-300 px-5 text-sm font-semibold text-gray-700 transition hover:bg-gray-50 dark:border-gray-700 dark:text-gray-300 dark:hover:bg-white/[0.05]">Cancelar</button><button type="submit" wire:loading.attr="disabled" wire:target="save" class="h-11 rounded-xl bg-brand-500 px-5 text-sm font-semibold text-white transition hover:bg-brand-600 disabled:opacity-70"><span wire:loading.remove wire:target="save">{{ $editingPresentationId === null ? 'Registrar presentación' : 'Guardar cambios' }}</span><span wire:loading wire:target="save">Guardando...</span></button></div>
            </form>
        </div>
    </div>

    <div wire:show="showStatusModal" x-cloak x-on:keydown.escape.window="$wire.closeStatusModal()" class="fixed inset-0 z-99999 flex items-center justify-center p-5" role="alertdialog" aria-modal="true" aria-labelledby="article-presentation-status-title">
        <button type="button" wire:click="closeStatusModal" class="fixed inset-0 h-full w-full cursor-default bg-gray-950/55 backdrop-blur-sm" aria-label="Cerrar confirmación"></button>
        <div class="relative w-full max-w-md rounded-3xl bg-white p-6 text-center shadow-theme-xl dark:bg-gray-900"><span class="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl {{ $statusPresentationIsActive ? 'bg-error-50 text-error-600 dark:bg-error-500/10 dark:text-error-400' : 'bg-success-50 text-success-600 dark:bg-success-500/10 dark:text-success-400' }}"><svg class="h-7 w-7" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 9v4M12 17h.01M10.3 4.4 2.7 18a2 2 0 0 0 1.75 3h15.1a2 2 0 0 0 1.75-3L13.7 4.4a2 2 0 0 0-3.4 0Z" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" /></svg></span><h2 id="article-presentation-status-title" class="mt-5 text-lg font-semibold text-gray-900 dark:text-white">{{ $statusPresentationIsActive ? '¿Desactivar esta presentación?' : '¿Activar esta presentación?' }}</h2><p class="mt-2 text-sm leading-6 text-gray-500 dark:text-gray-400"><strong class="font-semibold text-gray-700 dark:text-gray-300">{{ $statusPresentationName }}</strong> {{ $statusPresentationIsActive ? 'dejará de estar disponible para nuevas operaciones, pero conservará su historial.' : 'volverá a estar disponible para nuevas operaciones.' }}</p><div class="mt-6 grid grid-cols-2 gap-3"><button type="button" wire:click="closeStatusModal" class="h-11 rounded-xl border border-gray-300 text-sm font-semibold text-gray-700 dark:border-gray-700 dark:text-gray-300">Cancelar</button><button type="button" wire:click="changeStatus" wire:loading.attr="disabled" wire:target="changeStatus" class="h-11 rounded-xl text-sm font-semibold text-white disabled:opacity-70 {{ $statusPresentationIsActive ? 'bg-error-500 hover:bg-error-600' : 'bg-success-500 hover:bg-success-600' }}"><span wire:loading.remove wire:target="changeStatus">{{ $statusPresentationIsActive ? 'Sí, desactivar' : 'Sí, activar' }}</span><span wire:loading wire:target="changeStatus">Procesando...</span></button></div></div>
    </div>
</div>
